trigger:
- main

variables:
  webAppName: 'JavaWebApp'
  environmentName: 'JavaWebApp'

pool:
  vmImage: 'Hosted Agent'

stages:
- stage: Build
  displayName: Build stage
  jobs: 
  - job: MavenPackageAndPublishArtifact
    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'myRepoForJava/pom.xml'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: "Azure Web App Deploy: $(webAppName)"
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/JavaHelloWorldApp.war'
